// <auto-generated />
using GSULibrary.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GSULibrary.Migrations
{
    [DbContext(typeof(GSUBookContext))]
    partial class GSUBookContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("GSULibrary.Models.GSUBook", b =>
                {
                    b.Property<int>("GSUBookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberOfCopy")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("GSUBookId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            GSUBookId = 1,
                            Author = "Robert C. Martin",
                            ISBN = "978-0132350884",
                            Name = "Clean Code",
                            NumberOfCopy = 3,
                            Price = 35.99m
                        },
                        new
                        {
                            GSUBookId = 2,
                            Author = "Gang of Four",
                            ISBN = "978-0201633610",
                            Name = "Design Patterns",
                            NumberOfCopy = 1,
                            Price = 54.99m
                        },
                        new
                        {
                            GSUBookId = 3,
                            Author = "David Thomas",
                            ISBN = "978-0135957059",
                            Name = "The Pragmatic Programmer",
                            NumberOfCopy = 2,
                            Price = 49.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
